### PR TITLE
Add apiserver SNI support.

### PR DESCRIPTION
**Pull request by Gerrit91**

### CODE REVIEW

**Comment by majst01** [comment]
To make this as narrow as possible the following solution was created together with @rfranzke 

The APIServerSNI ist terminated in the `istio-ingressgateway` Service in the `istio-ingress` namespace in the Seed. But the namespace is configurable in:

https://github.com/gardener/gardener/blob/master/example/20-componentconfig-gardenlet.yaml#L108-L113

We should configure this namespace in our profile and then we can:
- check if this namespace exists in the seed
- if yes take the address of the `istio-ingressgateway` Service
- if not do not apply this additional CWNP

**Comment by mwennrich** [comment]
according to https://github.com/gardener/gardener/blob/master/docs/proposals/08-shoot-apiserver-via-sni.md the istio-envoy listens on the apiserver-ip port 8443:
```
        proxy_pass api.<external-domain>:8443;
```
So opening firewall to api-server port 8443 should be sufficient.

**Comment by majst01** [comment]
Sure but we wouldnt open to 0.0.0.0/0, restricting it to the real api server ip is required.

**Comment by majst01** [comment]
related to #154

**Comment by majst01** [comment]
Even duplicate of #154

**Pull request closed without merging**
