### PR TITLE
enable linter, update to g/g 1.30.2, update to go 1.18

### PR DESCRIPTION
**Pull request by majst01**
replaces #214

### CODE REVIEW

**Comment by Gerrit91** [comment]
With just linter fixes we can merge immediately, don't think the Gardener update is necessary right now? 
The linter action introduces double-linting, effectively increasing the build time. Maybe we can try providing an own config file in order not to slow down the build even further: https://github.com/gardener/gardener/blob/v1.27.5/hack/check.sh#L23

**Review by mwennrich — APPROVED** [review]

**Comment by majst01** [comment]
I would merge with the g/g update and use this for the next round of g/g update in our environment

**Comment by Gerrit91** [comment]
I don't think we need the Gardener dependency update because the other extension providers from them also only have builds for 1.27 or 1.29.

**Comment by Gerrit91** [comment]
Also why 1.28.0 and not the latest patch version of this release?

**Comment by majst01** [comment]
What about going to 1.30 straight ?

**Comment by majst01** [comment]
> Can you rebase and maybe even rename the branch? We can soon proceed with Gardener 1.30 and this PR would be great for that.

Branch rename would make this PR invalid, keep it

**Review by Gerrit91 — APPROVED** [review]

**Comment by mwennrich** [comment]
not so important, but mcm-deps could also be bumped: https://github.com/metal-stack/releases/blob/v0.10.2/release.yaml#L54-L61

**Review by mwennrich — APPROVED** [review]

**Comment by Gerrit91** [comment]
Will do this in the Gardener 1.31 PR. :)

**Pull request merged**
