### PR TITLE
Revert "Allow port 8443 in shoots for APIServerSNI feature gate"

### PR DESCRIPTION
**Pull request by majst01**
Reverts metal-stack/gardener-extension-provider-metal#117

### CODE REVIEW

**Review by Gerrit91 — APPROVED** [review]
Yep, sorry for that. I was so enthusiastic after enabling our pipeline for external contributors that I just merged this. :sweat: 

/cc @mvladev

**Comment by rfranzke** [comment]
What's the issue?

**Comment by majst01** [comment]
Problem is that with this cwnp we allow 8443 access to arbitrary destinations, this is contrary to the "need to know" principle.
Is it possible to put as destination der api-server address ?

**Comment by rfranzke** [comment]
It should be the address of the istio-ingressgateway load balancer IP, but generally yes. Though, I'm wondering what's the difference compared to all other CWNP you create. They are all using `0.0.0.0/0` and whitelist certain ports. For example, the `4314` port is also opened similarly.

**Comment by majst01** [comment]
The actual List is the result of a longish discussion and was only allowed because we where able to argue that this is the bare minimum.

**Comment by rfranzke** [comment]
Hm, OK, I'm still confused. Now the bare minimum got larger (+1 port) because a new feature was implemented. The feature is still alpha/disabled by default, but eventually it will graduate and probably the non-configurable default, and at latest then it needs to be opened.
I agree/understand that you are not happy with the fact that most rules already allow `0.0.0.0/0`, but I don't get why it's a problem to add another port now. The whole CWNP could be refactored to make them more strict, but as long as this isn't done and all the other rules stay as they are it doesn't matter (from my pov) to add one additional port that is mandatory anyways soon.

**Comment by majst01** [comment]
OK, will discuss internally with team and come back on this. Thanks for you patience

**Comment by majst01** [comment]
created new PR: https://github.com/metal-stack/gardener-extension-provider-metal/pull/128

**Pull request merged**
