### PR TITLE
Make storageclass configurable per seed

### PR DESCRIPTION
**Pull request by majst01**

### CODE REVIEW

**Comment by mwennrich** [comment]
There are three volumes in a seed cluster, what about the others?

Three per shoot:
```plaintext
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
etcd-events-etcd-events-0    Bound    pvc-e0979815-08e6-4482-a097-d2e0791b5d08   16Gi       RWO            csi-lvm        352d
main-etcd-etcd-main-0        Bound    pvc-f1e7df66-0c14-44c1-933c-c8e6f4b5dc43   16Gi       RWO            csi-lvm        352d
prometheus-db-prometheus-0   Bound    pvc-ef72b77d-b76b-4b3e-af60-2e26217d069b   20Gi       RWO            csi-lvm        175d
```

And two in the garden namespace:
```plaintext
NAMESPACE                   NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
garden                      prometheus-db-aggregate-prometheus-0   Bound    pvc-b40590e4-3274-439f-b81a-23de8e3a6402   20Gi       RWO            csi-lvm        696d
garden                      prometheus-db-prometheus-0             Bound    pvc-b18e8257-d13a-4c7c-8f14-876e192e20af   10Gi       RWO            csi-lvm        696d
```

**Comment by majst01** [comment]
> There are more volumes in a seed cluster, what about the others?
> 
> Three per shoot:
> 
> ```
> NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> etcd-events-etcd-events-0    Bound    pvc-e0979815-08e6-4482-a097-d2e0791b5d08   16Gi       RWO            csi-lvm        352d
> main-etcd-etcd-main-0        Bound    pvc-f1e7df66-0c14-44c1-933c-c8e6f4b5dc43   16Gi       RWO            csi-lvm        352d
> prometheus-db-prometheus-0   Bound    pvc-ef72b77d-b76b-4b3e-af60-2e26217d069b   20Gi       RWO            csi-lvm        175d
> ```
> 
> And two in the garden namespace:
> 
> ```
> NAMESPACE                   NAME                                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> garden                      prometheus-db-aggregate-prometheus-0   Bound    pvc-b40590e4-3274-439f-b81a-23de8e3a6402   20Gi       RWO            csi-lvm        696d
> garden                      prometheus-db-prometheus-0             Bound    pvc-b18e8257-d13a-4c7c-8f14-876e192e20af   10Gi       RWO            csi-lvm        696d
> ```

We thought using this for the etcd-main would suffice, but if we do not change this for the other statefulsets as well, we will always need manual intervention on node rollings.

It still feels weird.

**Comment by majst01** [comment]
maybe we should instead add a configurationOption in the infrastructureConfig SeedConfigs which has a field DefaultStorageClassName, which disables the default StorageClass reconcile for the csi-lvm and set the required annotation to the SC with the given name.

**Comment by mwennrich** [comment]
If we make the storageclass configurable per shoot ("shooted seed"), this would also solve #233

**Comment by majst01** [comment]
> maybe we should instead add a configurationOption in the infrastructureConfig SeedConfigs which has a field DefaultStorageClassName, which disables the default StorageClass reconcile for the csi-lvm and set the required annotation to the SC with the given name.

Correction: Shoud be a field in the Shoot spec i guess

**Pull request closed without merging**
