### PR TITLE
Added cluster identifier to splunk auditing and change to static webhook deployment

### PR DESCRIPTION
**Pull request by mreiger**
Pass a cluster identifier (Tenant-ProjectID-ClusterName) to the splunk audit webhook so the cluster can be identified in the splunk data. It gets passed along to splunk in the "hostname" field of the splunk event.

Also changed to static webhook deployment because dynamic auditsink resource will probably get removed in future K8s versions.

### CODE REVIEW

**Comment by Gerrit91** [comment]
Only thing that is confusing me a little is the naming. Why is it called `host` when it is actually not a hostname or something but a cluster identifier?

**Comment by mreiger** [comment]
It is called `host` because it fills the field `hostname`. In the webhook I called the option `host` because the webhook is not actually restricted to Kubernetes clusters, so `cluster` seemed a little weird.

Do you have a suggestion for a less ambiguous name?

**Comment by Gerrit91** [comment]
It's certainly enough to just clarify it in the chart, no need to change anything in the webhook project. Maybe something like "source_hostname" would be a little more self-explanatory?

**Review by Gerrit91 — APPROVED** [review]
Tried out in test environment, which was working.

**Pull request merged**
