### PR TITLE
Allow port 8443 in shoots for APIServerSNI feature gate

### PR DESCRIPTION
**Pull request by rfranzke**
/cc @mvladev @gehoern

### CODE REVIEW

**Comment by majst01** [comment]
@rfranzke great to see you guys using our stuff :+1:

**Comment by Gerrit91** [comment]
May I ask you to pull the changes from the current tip of the master branch into this? I think, this would resolve the pipeline failure.

#118

**Comment by rfranzke** [comment]
@majst01 same vice versa 😄

**Comment by rfranzke** [comment]
@Gerrit91 done

**Comment by Gerrit91** [comment]
I'm sorry, seems like this did not work. I will try to figure out another method of doing this and test it by myself before. Github Actions... sometimes they can be very painful. :(

**Comment by Gerrit91** [comment]
After a myriad of attempts, if you pull in the master, your pipeline should succeed now. I tested it with an own forked PR.

**Review by Gerrit91 — APPROVED** [review]

**Comment by majst01** [comment]
Already merged, one nit, is it possible to check if this feature gate is enabled, and can we restrict to the API server IP ?

**Comment by rfranzke** [comment]
cc @mvladev - can you help with that question?

**Comment by majst01** [comment]
Sorry, was merged by accident, have to revert until we found a solution to restrict to a specific CIDR and only for the featuregate is enabled

**Comment by majst01** [comment]
@mvladev can you explain where we can access the feature gate "APIServerSNI" to make the CWNP conditional regarding adding this rule ?

**Comment by majst01** [comment]
We are preparing a slightly modified version here: https://github.com/metal-stack/gardener-extension-provider-metal/pull/128

**Pull request merged**
