### PR TITLE
Restrict-droptailer

### PR DESCRIPTION
**Pull request by mwennrich**
-   restrict egress traffic for droptailer
  -   disable automountServiceAccountToken for droptailer

### CODE REVIEW

**Comment by majst01** [comment]
maybe we should also change to a deployment and service instead of a simple pod

**Comment by Gerrit91** [comment]
I guess this is not so easy because the firewall-controller implementation also needs to change then: https://github.com/metal-stack/firewall-controller/blob/master/controllers/droptailer_controller.go#L88-L91

**Comment by majst01** [comment]
> I guess this is not so easy because the firewall-controller implementation also needs to change then: https://github.com/metal-stack/firewall-controller/blob/master/controllers/droptailer_controller.go#L88-L91

But this can be done afterwards, because a pod still exists
Downside: if droptailer is exposed as a service, it gets exposed to the outer world

**Comment by majst01** [comment]
From integration test cluster:
```
k get -n firewall pod droptailer-55f6669586-h2qts -o yaml | grep auto
  automountServiceAccountToken: false

k get netpol -n firewall
NAME         POD-SELECTOR         AGE
droptailer   k8s-app=droptailer   34m


stern -n firewall drop --tail 3
+ droptailer-55f6669586-h2qts › droptailer
droptailer-55f6669586-h2qts droptailer 2022-01-12 12:03:07 +0000 UTC {"DPT":"5953","DST":"1.2.3.4","ID":"49360","IN":"vrf104009","LEN":"40","MAC":"02:ba:15:b3:2d:8f:b8:6a:97:73:f7:3a:08:00","OUT":"","PREC":"0x00","PROTO":"TCP","RES":"0x00","SPT":"44176","SRC":"193.201.9.126","SYN":"","TOS":"0x00","TTL":"247","URGP":"0","WINDOW":"1024","timestamp":"2022-01-12 12:03:07 +0000 UTC"}
```

**Review by majst01 — APPROVED** [review]

**Review by Gerrit91 — APPROVED** [review]

**Pull request merged**
